
package rrr;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class ViewBokking extends javax.swing.JFrame {

    /**
     * Creates new form vviewBokking
     */
    public ViewBokking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        main = new javax.swing.JButton();
        viewBokking = new javax.swing.JButton();
        Rewiew = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trip Rewiew");

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 73, 144));
        jLabel1.setText("Please enter your phone number");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrr/الشعار معدل.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        main.setBackground(new java.awt.Color(204, 255, 255));
        main.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        main.setForeground(new java.awt.Color(14, 73, 144));
        main.setText("Back");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        viewBokking.setBackground(new java.awt.Color(204, 255, 255));
        viewBokking.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        viewBokking.setForeground(new java.awt.Color(14, 73, 144));
        viewBokking.setText("View Booking");
        viewBokking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBokkingActionPerformed(evt);
            }
        });

        Rewiew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RewiewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(viewBokking)
                        .addGap(121, 121, 121)
                        .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(Rewiew, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {main, viewBokking});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Rewiew, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBokking))
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {main, viewBokking});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RewiewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RewiewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RewiewActionPerformed

    private void viewBokkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBokkingActionPerformed
                                      
    try {
        Connection conn = DBConnection.connect(); 

        String sql = "SELECT customerFname, customerLname, phone, " +
                     "tripType, tripDate, passengersNum, price " +
                     "FROM Customer " +
                     "INNER JOIN Booking b ON Customer.customerID = b.customerID " +
                     "WHERE phone = ?";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, Rewiew.getText().trim());

        ResultSet bookingData = pst.executeQuery();

        if (bookingData.next()) {

            String TripInformation =
                "First Name: " + bookingData.getString("customerFname") + "\n" +
                "Last Name: " + bookingData.getString("customerLname") + "\n" +
                "Phone: " + bookingData.getString("phone") + "\n\n" +
                "Booking Details:\n" +
                "Trip Type: " + bookingData.getString("tripType") + "\n" +
                "Trip Date: " + bookingData.getString("tripDate") + "\n" +
                "Passengers: " + bookingData.getString("passengersNum") + "\n" +
                "Price: " + bookingData.getString("price");

            JOptionPane.showMessageDialog(this, TripInformation,
                "Trip Review", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this,
                "Dear Customer,\n" +
                "We would like to inform you that there are currently no bookings under your number.\n" +
                "Please check the phone number and try again.",
                "No Booking Found",
                JOptionPane.INFORMATION_MESSAGE);
        }

        conn.close(); 

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
    }


          
    }//GEN-LAST:event_viewBokkingActionPerformed

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
 this.setVisible (false);
new HomeForm().setVisible(true) ;
    }//GEN-LAST:event_mainActionPerformed

    
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vviewBokking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vviewBokking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vviewBokking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vviewBokking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBokking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rewiew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton main;
    private javax.swing.JButton viewBokking;
    // End of variables declaration//GEN-END:variables
}
